/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.lightningdevkit.orangesdk

import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import org.junit.runner.RunWith
import org.lightningdevkit.orangesdk.*

@RunWith(AndroidJUnit4::class)
class AndroidLibTest {
    @Test
    fun node_start_stop() {
        println("Add a simple test here")
    }
}