name: Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust_tests:
    name: Rust Checks
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "30.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: ./ci/check-lint.sh

      - name: Check examples
        run: cargo check -p orange-cli

      - name: Run tests
        run: cargo test --features _test-utils -- --test-threads=2

  cashu_tests:
    name: Cashu Tests
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "30.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Run cashu tests
        run: cargo test --features _cashu-tests -- --test-threads=2
